services:
  - name: django
    type: web
    env: docker
    buildCommand: ""
    startCommand: gunicorn pet_project.wsgi:application --bind 0.0.0.0:8000
    dockerfilePath: Dockerfile
    envVars:
      STRIPE_PUBLISHABLE_KEY: 'pk_test_51PLAVyDo5uaPJl4sZnu2nfKjDPjFQqgc24tfaMw4JnE0QsaVxRJ7tWiaUKpnFduAPfQbJpzr7Mge1d2wkNocl1hU00YSQk285H'
      STRIPE_SECRET_KEY: 'sk_test_51PLAVyDo5uaPJl4svwhpMCwmcRdLWVQjKmNm8ddxkxBh1ZrJtMDXqeQDpmeuuU2QPrONZurEjF6V3djGWlsT6mjc00pIB7NZLp'
      STRIPE_WEBHOOK_SECRET: 'whsec_o4MTEkPB8tYpojzDIz8Llk7X47dOG4iw'
      CELERY_BROKER_URL: 'redis://red-crrgv9dumphs73b9l700:6379'

  - name: postgres
    type: database
    plan: starter
    version: 15

  - name: redis
    type: redis
    plan: free

  - name: celery
    type: worker
    env: docker
    dockerfilePath: Dockerfile
    startCommand: celery -A pet_project worker --loglevel=info -P eventlet
    envVars:
      CELERY_BROKER_URL: 'redis://red-crrgv9dumphs73b9l700:6379'

  - name: celery-beat
    type: worker
    env: docker
    dockerfilePath: Dockerfile
    startCommand: celery -A pet_project beat --loglevel=info -P eventlet
    envVars:
      CELERY_BROKER_URL: 'redis://red-crrgv9dumphs73b9l700:6379'

  - name: nginx
    type: web
    env: docker
    buildCommand: ""
    startCommand: ""
    dockerfilePath: Dockerfile
    envVars:
      NGINX_CONFIG_PATH: "/etc/nginx/nginx.conf"
    files:
      - path: /etc/nginx/nginx.conf
        source: ./nginx.conf

  - name: flower
    type: worker
    env: docker
    dockerfilePath: Dockerfile
    startCommand: celery -A pet_project flower --port=5555
