# Generated by Django 5.0.3 on 2024-05-13 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.RemoveField(
            model_name='categorytranslation',
            name='description',
        ),
    ]
