# Generated by Django 5.0.3 on 2024-05-13 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_remove_category_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brandtranslation',
            name='name',
        ),
        migrations.RemoveField(
            model_name='brandtranslation',
            name='slug',
        ),
        migrations.AddField(
            model_name='brand',
            name='name',
            field=models.CharField(db_index=True, default=1, max_length=100, verbose_name='name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brand',
            name='slug',
            field=models.SlugField(default=1, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
