# Generated by Django 5.0.3 on 2024-05-13 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_remove_brandtranslation_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttranslation',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='catalog.category', verbose_name='category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_brand', to='catalog.category', verbose_name='brand'),
        ),
    ]
