# Generated by Django 5.0.3 on 2024-05-15 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorytranslation',
            old_name='_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
    ]
