# Generated by Django 5.0.3 on 2024-05-23 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_alter_categorytranslation_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='availability',
            field=models.BooleanField(default=True, verbose_name='availability'),
        ),
    ]
